name: End-to-end tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  end-to-end:
    runs-on: ubuntu-22.04
    name: Cypress run
    env:
      CI: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run end-to-end tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: test/cypress/screenshots
      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: test/cypress/videos
